[package]
name = "stealth_addresses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "0.14.7"
hex = "0.4.3"
k256 = "0.13.1"
rand = "0.8.5"
secp256k1 = "0.27.0"
sha3 = "0.10.8"
